#!/usr/bin/env python3

import argparse
import pathlib


TEST_SRC_DIR = pathlib.Path(__file__).parent.resolve()


def sync(dockerfiles, prefix, tag):
    if not dockerfiles:
        dockerfiles = list((TEST_SRC_DIR / 'images').glob('*.dockerfile'))

    for dockerfile in dockerfiles:
        pathlib.Path(dockerfile).write_text(f'FROM {prefix}{dockerfile.stem}:{tag}\n')


def main(*args, **kwargs):
    parser = argparse.ArgumentParser(
        description='Switch container image tag',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument(
        '--file', '-f',
        action='append',
        dest='dockerfiles',
        help="Dockerfiles to update. Update all if not specified"
    )

    parser.add_argument(
        '--prefix', '-p',
        default='ghcr.io/ddterm/gnome-shell-pod/',
        help="Image name prefix"
    )

    parser.add_argument(
        'tag',
        help="Image tag"
    )

    sync(**vars(parser.parse_args(*args, **kwargs)))


if __name__ == '__main__':
    main()
