# SPDX-FileCopyrightText: 2023 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

changelog:
  exclude:
    authors:
      - 'renovate'
      - 'renovate[bot]'
      - 'ddterm-automation'
      - 'ddterm-automation[bot]'
