# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[tool.bumpversion]
current_version = "58"
parse = "(?P<major>\\d+)"
serialize = ["{major}"]

[[tool.bumpversion.files]]
filename = "meson.build"
search = "version: '{current_version}'"
replace = "version: '{new_version}'"

[[tool.bumpversion.files]]
filename = "PKGBUILD"
search = "pkgver={current_version}"
replace = "pkgver={new_version}"
