root: true

extends:
  - ./lint/eslintrc-ddterm-common.yml

overrides:
  - files:
      - tools/import-resolver.js
    parserOptions:
      sourceType: commonjs
    env:
      node: true
  - files:
      - bin/launcher.js
    parserOptions:
      sourceType: script
