extends:
 - ./lint/eslintrc-gjs.yml

rules:
  max-len:
    - error
    - 100
  consistent-return: error
  key-spacing:
    - error
    - mode: minimum
      beforeColon: false
      afterColon: true
  object-curly-spacing:
    - error
    - always
  prefer-arrow-callback: error
  no-multiple-empty-lines:
    - error
    - max: 1
  jsdoc/require-jsdoc: off
globals:
  global: readonly
parserOptions:
  ecmaVersion: 2020
overrides:
  - files:
      - ddterm/app/**
      - ddterm/pref/test/**
      - ddterm/util/**
    parserOptions:
      sourceType: module
