root: true

extends:
  - ./lint/eslintrc-ddterm-common.yml

overrides:
  - files:
      - lint/import-resolver.js
    parserOptions:
      sourceType: commonjs
    env:
      node: true
  - files:
      - extension.legacy.js
      - prefs.legacy.js
      - ddterm/app/fakeext/misc/extensionUtils.js
      - ddterm/pref/resources.legacy.js
      - ddterm/shell/compat.js
      - test/extension-legacy/*.js
      - bin/launcher.js
      - tools/translate-esm.js
    parserOptions:
      sourceType: script
