# SPDX-FileCopyrightText: 2024 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-cli2-config-schema.json

# config: won't work here, use .markdownlint.yml instead

globs:
  - '**/*.md'
gitignore: true
ignores:
  - tools/heapgraph.md
customRules:
  - markdownlint-rule-relative-links
