# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

no-blanks-blockquote: false

ol-prefix:
  style: ordered

no-inline-html:
  allowed_elements:
    - kbd

link-image-style:
  inline: false
  url_inline: false

relative-links:
  root_path: .
