# SPDX-FileCopyrightText: 2026 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[weblate]
url = https://hosted.weblate.org/api/
translation = gnome-shell-extension-ddterm/extension
