# SPDX-FileCopyrightText: 2024 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

SPDX-PackageName = "gnome-shell-extension-ddterm"
SPDX-PackageOriginator = "Aleksandr Mezin <mezin.alexander@gmail.com>"
SPDX-PackageHomePage = "https://github.com/ddterm/gnome-shell-extension-ddterm/"
SPDX-PackageLicenseDeclared = "GPL-3.0-or-later"

[[annotations]]
path = "locale/**/LC_MESSAGES/*.mo"
SPDX-FileCopyrightText = "ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-License-Identifier = "GPL-3.0-or-later"
