# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run REUSE lint
description: Check repository REUSE compliance

runs:
  using: composite
  steps:
    - id: reuse-problem-matcher
      uses: ./.github/actions/reuse-problem-matcher

    - run: tox --no-list-dependencies -q -e reuse -- lint --lines
      shell: bash

    - uses: ./.github/actions/reuse-problem-matcher
      with:
        enable: false
      if: ${{ !cancelled() && steps.reuse-problem-matcher.outcome == 'success' }}
