# SPDX-FileCopyrightText: 2026 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Initialize APT
description: Configure and update APT repositories

runs:
  using: composite
  steps:
    - shell: sudo bash -e {0}
      run: |
        sed -i -E 's/^(Components:.*)\srestricted(.*)$/\1\2/g' /etc/apt/sources.list.d/ubuntu.sources
        sed -i -E 's/^(Components:.*)\smultiverse(.*)$/\1\2/g' /etc/apt/sources.list.d/ubuntu.sources
        sed -i -E 's/^(Suites:.*)\snoble-backports(.*)$/\1\2/g' /etc/apt/sources.list.d/ubuntu.sources

        shopt -s extglob
        rm -f /etc/apt/sources.list.d/!(ubuntu.sources)

    - shell: sudo bash -e {0}
      run: apt-get update
