# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Get list of files changed in push/pull request
description: Get the list of all files affected by push/pull request event
inputs:
  repository:
    description: Repository name
    default: ${{ github.event.repository.name }}
    required: true
  owner:
    description: Repository owner
    default: ${{ github.repository_owner }}
    required: true
  head:
    description: New head commit
    default: ${{ github.sha }}
    required: true
  base:
    description: Base commit to diff against
    default: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.before }}
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

outputs:
  filenames:
    description: Pathnames of all affected files, as JSON list
    value: ${{ steps.compare.outputs.result }}

runs:
  using: composite
  steps:
    - name: Compare commits
      id: compare
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { data } = await github.request('GET /repos/{owner}/{repo}/compare/{base}...{head}', {
            repo: core.getInput('repository', { required: true }),
            owner: core.getInput('owner', { required: true }),
            base: core.getInput('base', { required: true }),
            head: core.getInput('head', { required: true }),
          });

          if (data.files.length === 300) {
            throw new Error('Response is too large, most likely it was truncated');
          }

          return data.files.map(f => f.filename);

      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_BASE: ${{ inputs.base }}
        INPUT_HEAD: ${{ inputs.head }}
