# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run flake8
description: Run flake8 with SARIF report

runs:
  using: composite
  steps:
    - run: tox -e flake8 -- "--append-config=$GITHUB_ACTION_PATH/config.ini" --format=sarif-tee "--output-file=$RUNNER_TEMP/flake8.sarif"
      shell: bash

    - id: env
      run: |
        echo "github_workspace=$GITHUB_WORKSPACE" >>"$GITHUB_OUTPUT"
        echo "runner_temp=$RUNNER_TEMP" >>"$GITHUB_OUTPUT"
      shell: bash
      if: always()

    - uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
      if: always()
      with:
        sarif_file: ${{ steps.env.outputs.runner_temp }}/flake8.sarif
        checkout_path: ${{ steps.env.outputs.github_workspace }}
        category: flake8
