# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run flake8
description: Run flake8 with error annotations

runs:
  using: composite
  steps:
    - id: flake8-problem-matcher
      uses: ./.github/actions/generic-problem-matcher

    - run: tox -e flake8
      shell: bash
      env:
        FORCE_COLOR: 0

    - uses: ./.github/actions/generic-problem-matcher
      with:
        enable: false
      if: ${{ always() && steps.flake8-problem-matcher.outcome == 'success' }}
