# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Create pull request
description: Create a pull request adding/updating the specified files

inputs:
  app-id:
    description: App ID
    required: true

  private-key:
    description: App private key
    required: true

  title:
    description: Pull request and commit title
    required: true

  description:
    description: Pull request and commit description
    required: false

  files:
    description: List of files/glob patterns to include in the commit and pull request, one per line
    required: true

  branch:
    description: Branch name (without refs/heads/)
    default: ${{ github.job }}
    required: true

runs:
  using: composite
  steps:
    - id: token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        permission-contents: write
        permission-pull-requests: write

    - id: commit
      uses: amezin/create-commit-action@d99c43768be65bc91e6dfecd1340e5e91da756b8 # v2.0.2
      with:
        github-token: ${{ steps.token.outputs.token }}
        files: ${{ inputs.files }}
        message: |
          ${{ inputs.title }}

          ${{ inputs.description }}

    - uses: amezin/create-or-update-git-ref-action@56a1c2e2ba60d79a65210a2b2d9279599f9f35d2 # v2.0.1
      with:
        github-token: ${{ steps.token.outputs.token }}
        sha: ${{ steps.commit.outputs.sha }}
        ref: refs/heads/${{ inputs.branch }}
        force: true

    - uses: amezin/create-or-update-pull-request-action@3b546ed950876fb5061fb16d5fd9e97e359eac8f # v2.0.1
      with:
        github-token: ${{ steps.token.outputs.token }}
        head: ${{ inputs.branch }}
        title: ${{ inputs.title }}
        body: |
          ${{ inputs.description }}

          Automatically generated pull request, do not edit. Any changes will be overwritten.
