# SPDX-FileCopyrightText: 2022 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Bug Report
description: Something is not working as described, unexpected error messages, etc.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Please check GNOME session logs for relevant error messages:
          - `journalctl --user -b` on systemd-based operating systems
          - `~/.cache/gdm/session.log` otherwise

        If you were experimenting with other window management extensions,
        recently updated ddterm through your distribution's package manager,
        or built it from source, please ensure the bug persists after you
        log out and log in again - i. e. after GNOME Shell has restarted.

  - type: input
    id: shell-version
    attributes:
      label: GNOME Shell version
      description: >
        Output of `gnome-shell --version`
      placeholder: gnome-shell --version

  - type: input
    id: distro
    attributes:
      label: Linux distro
      description: >
        Output of `grep -Po '^PRETTY_NAME=\K.*' /etc/os-release`
      placeholder: grep -Po '^PRETTY_NAME=\K.*' /etc/os-release

  - type: textarea
    id: ddterm-versions
    attributes:
      label: ddterm version
      description: >
        Output of `com.github.amezin.ddterm --version || ~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm --version`
      placeholder: com.github.amezin.ddterm --version || ~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm --version

  - type: dropdown
    id: session-type
    attributes:
      label: Session type
      multiple: false
      options:
        - "X11"
        - "Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)"

  - type: checkboxes
    id: flags
    attributes:
      label: Special configuration
      options:
        - label: High DPI
        - label: More than one monitor

  - type: textarea
    id: extensions
    attributes:
      label: All installed extensions
      description: >
        Output of `gnome-extensions list -d`
      placeholder: gnome-extensions list -d
      render: Text

  - type: textarea
    id: dconf-dump
    attributes:
      label: ddterm settings dump
      description: >
        Output of `dconf dump /com/github/amezin/ddterm/`
      placeholder: dconf dump /com/github/amezin/ddterm/
      render: ini

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Description of the issue.

        Screenshots are appreciated, but not required.

        Also, you could save `journalctl --user -b` output to a file
        (`journactl --user -b >journal.txt`) and upload it here. However,
        check it for sensitive data before uploading (it may contain other
        application names, document/file names, window titles, etc.).

        On non-systemd distributions, session logs are located in
        `~/.cache/gdm/session.log`.

      placeholder: >
        Tip: You can attach images or log files by clicking this area to
        highlight it and then dragging files in.
