# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run tests in Podman container
description: Run tests in Podman container and upload reports

inputs:
  container:
    description: Container image or service name from tests/compose.yaml
    required: true
  user:
    description: User to run tests under
    default: github-actions
    required: true
  group:
    description: Group to run tests under
    default: github-actions
    required: true
  testspace:
    description: Upload results to testspace
    default: 'false'
    required: true
  args:
    description: Arguments to pass to the tests

runs:
  using: composite
  steps:
    - run: mount --make-rshared /
      shell: bash

    - id: root-cgroup
      run: grep '^0::' /proc/self/cgroup | sed 's/^0::/cgroup=/' | tee -a "$GITHUB_OUTPUT"
      shell: bash

    - run: chown -R "$TARGET_USER" "/sys/fs/cgroup${CGROUP}" "$GITHUB_WORKSPACE"
      shell: bash
      env:
        TARGET_USER: ${{ inputs.user }}:${{ inputs.group }}
        CGROUP: ${{ steps.root-cgroup.outputs.cgroup }}

    - shell: sudo --preserve-env --set-home --user=${{ inputs.user }} --group=${{ inputs.group }} -- bash -e {0}
      run: tox -e images -- pull "$CONTAINER"
      env:
        CONTAINER: ${{ inputs.container }}

    - id: setup-testspace
      uses: testspace-com/setup-testspace@5fc620521eddeba83c1c0dd58f5a524adf474c93 # v1.0.8
      with:
        domain: ${{ github.repository_owner }}
      continue-on-error: true
      if: fromJSON(inputs.testspace)

    - id: test
      shell: sudo --preserve-env --set-home --user=${{ inputs.user }} --group=${{ inputs.group }} -- bash -e {0}
      run: >-
        tox -e pytest --
        --self-contained-html
        --junitxml=tests/junit.xml
        "--container=$CONTAINER"
        -n auto
        -vv
        ${{ inputs.args }}
      env:
        CONTAINER: ${{ inputs.container }}

    - if: ${{ !cancelled() && steps.setup-testspace.outcome == 'success' }}
      shell: bash
      run: >-
        testspace --verbose
        "[$CONTAINER]./tests/junit.xml"
        "[$CONTAINER]+./tests/report.html"
      env:
        CONTAINER: ${{ inputs.container }}

    - if: ${{ !cancelled() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.container }}-reports
        path: |
          tests/report.html
          tests/junit.xml
