# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run markdownlint-cli2
description: Run markdownlint-cli2 with SARIF report

runs:
  using: composite
  steps:
    - run: npm run-script lint:markdownlint -- --config "$GITHUB_ACTION_PATH/github.markdownlint-cli2.mjs"
      shell: bash

    - id: env
      run: |
        echo "github_workspace=$GITHUB_WORKSPACE" >>"$GITHUB_OUTPUT"
        echo "runner_temp=$RUNNER_TEMP" >>"$GITHUB_OUTPUT"
      shell: bash
      if: always()

    - uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
      if: always()
      with:
        sarif_file: ${{ steps.env.outputs.runner_temp }}/markdownlint.sarif
        checkout_path: ${{ steps.env.outputs.github_workspace }}
        category: markdownlint
