# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: ESLint "stylish" problem matcher
description: Enable/disable ESLint "stylish" problem matcher
inputs:
  enable:
    description: Enable if `true`, disable if `false`
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - run: echo "::add-matcher::$GITHUB_ACTION_PATH/eslint-stylish.json"
      shell: sh
      if: fromJSON(inputs.enable)

    - run: echo "::remove-matcher owner=eslint-stylish::"
      shell: sh
      if: '!fromJSON(inputs.enable)'
