#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import os.path
import pathlib
import subprocess


def check_file_translatable(filepath, xgettext, xgettext_args):
    argv = [xgettext, *xgettext_args, '-o-', str(filepath)]
    return subprocess.check_output(argv).strip() != b''


def gen(files, root, xgettext, xgettext_args):
    root = root.resolve()

    content = sorted(
        filepath.resolve().relative_to(root)
        for filepath in files
        if check_file_translatable(filepath, xgettext, xgettext_args)
    )

    # REUSE-IgnoreStart
    print('# SPDX-FileCopyrightText: NONE')
    print('# SPDX-License-Identifier: CC0-1.0')
    print(
        f'# Generated by {os.path.basename(__file__)}, run "ninja potfiles" to update'
    )
    # REUSE-IgnoreEnd

    for filepath in content:
        print(str(filepath))


def cli():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-C', '--root', type=pathlib.Path, default=pathlib.Path.cwd())
    parser.add_argument('--xgettext', default='xgettext')
    parser.add_argument('-x', '--xgettext-args', action='append')
    parser.add_argument('files', type=pathlib.Path, nargs='+')

    gen(**vars(parser.parse_args()))


if __name__ == '__main__':
    cli()
