version = 1

[[annotations]]
path = [
  "cs.po",
  "cs/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = "Pavel Nov\u00e1k <pavelnov32@gmail.com>, 2023"

[[annotations]]
path = [
  "de.po",
  "de/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "J\u00f6rn Weigend <das.jott@gmail.com>, 2023",
  "Ettore Atalan <atalanttore@googlemail.com>, 2023",
  "Philipp Kiemle <philipp.kiemle@gmail.com>, 2023"
]

[[annotations]]
path = [
  "el.po",
  "el/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Anagnostakis Ioannis <rizitis@gmail.com>, 2023",
  "Klearchos-Angelos Gkountras <jemadux@cryptolab.net>, 2025"
]

[[annotations]]
path = [
  "eo.po",
  "eo/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2024 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = "phlostically <phlostically@mailinator.com>, 2024"

[[annotations]]
path = [
  "es.po",
  "es/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Adrian Alberdi Ainciburu <adrian1992@gmail.com>, 2023",
  "gallegonovato <fran-carro@hotmail.es>, 2023, 2024",
  "Patricio Carrau <66135366+DuckyCB@users.noreply.github.com>, 2024",
  "Patricio Carrau <duckycb@proton.me>, 2024, 2025"
]

[[annotations]]
path = [
  "fr.po",
  "fr/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2022 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Arnaud Feldmann <arnaud.feldmann@gmail.com>, 2023, 2024",
  "fail a fail <yassadmi@proton.me>, 2023",
  "Stephane LE CAER <stephane@slc66.net>, 2023",
  "Patricio Carrau <duckycb@proton.me>, 2024"
]

[[annotations]]
path = [
  "it.po",
  "it/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Matteo Cerri <mttcerri@hotmail.com>, 2023",
  "Frankie McEyes <mceyes@protonmail.com>, 2023",
  "Nathan Hadley <nathanhadley.pigeon@gmail.com>, 2024"
]

[[annotations]]
path = [
  "nb_NO.po",
  "nb_NO/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = "Allan Nordh\u00f8y <epost@anotheragency.no>, 2023, 2024"

[[annotations]]
path = [
  "pl.po",
  "pl/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Micha\u0142 Olejniczak <blind.x6@gmail.com>, 2023",
  "Eryk Michalak <gnu.ewm@protonmail.com>, 2023",
  "Defender94 <defender94.business@gmail.com>, 2023",
  "luk <luktvpl@wp.pl>, 2024",
  "Wojciech Teichert <wojtekt99@gmail.com>, 2024",
  "luk <lukasz.osadik@wp.pl>, 2025"
]

[[annotations]]
path = [
  "pt.po",
  "pt/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Cezar Cruz <cezarcruz@outlook.com>, 2023",
  "Luiz Carlos de Souza Santos <lcdessantos@gmail.com>, 2023",
  "Bruno Rodrigues <b.rodrigues@live.com>, 2024"
]

[[annotations]]
path = [
  "ru.po",
  "ru/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2022 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "vantu5z <vantu5z@mail.ru>, 2022-2023",
  "Aleksandr Mezin <mezin.alexander@gmail.com>, 2023, 2024",
  "Ivan Vantu5z <vantu5z@mail.ru>, 2023",
  "gfbdrgng <hnaofegnp@hldrive.com>, 2023",
  "Dmitriy Q <krotesk@mail.ru>, 2024",
  "Stepan <stepan.miroshnikov@gmail.com>, 2024"
]

[[annotations]]
path = [
  "tr.po",
  "tr/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2024 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = [
  "Mustafa Kemal Gilor <mustafa.gilor@canonical.com>, 2024",
  "Muha Aliss <muhaaliss@users.noreply.hosted.weblate.org>, 2024",
  "Nuri K\u00dc\u00c7\u00dcKLER <enatsek@gmail.com>, 2025"
]

[[annotations]]
path = [
  "zh_CN.po",
  "zh_CN/LC_MESSAGES/ddterm@amezin.github.com.mo"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2023 ddterm contributors <https://github.com/ddterm/gnome-shell-extension-ddterm/>"
SPDX-FileContributor = "yuh <yuhldr@qq.com>, 2023, 2024"
