# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Run actionlint
description: Run actionlint with error annotations

inputs:
  actionlint-version:
    # renovate: datasource=github-releases depName=rhysd/actionlint
    default: '1.7.10'
    description: actionlint version

runs:
  using: composite
  steps:
    - working-directory: ${{ runner.temp }}
      shell: bash
      env:
        ACTIONLINT_VERSION: ${{ inputs.actionlint-version }}

      run: |
        curl -LO "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
        mkdir -p "actionlint-${ACTIONLINT_VERSION}"
        tar -C "actionlint-${ACTIONLINT_VERSION}" -xf "actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
        echo "$(pwd)/actionlint-${ACTIONLINT_VERSION}" >>"$GITHUB_PATH"

    - id: actionlint-problem-matcher
      working-directory: ${{ runner.temp }}
      shell: bash
      env:
        ACTIONLINT_VERSION: ${{ inputs.actionlint-version }}

      run: |
        curl -LO "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/.github/actionlint-matcher.json"
        echo "::add-matcher::$(pwd)/actionlint-matcher.json"

    - run: actionlint -verbose -color
      shell: bash

    - run: echo '::remove-matcher owner=actionlint::'
      shell: bash
      if: ${{ !cancelled() && steps.actionlint-problem-matcher.outcome == 'success' }}
