# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE tool problem matcher
description: Enable/disable REUSE tool problem matcher
inputs:
  enable:
    description: Enable if `true`, disable if `false`
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - run: echo "::add-matcher::$GITHUB_ACTION_PATH/reuse.json"
      shell: sh
      if: fromJSON(inputs.enable)

    - run: echo "::remove-matcher owner=reuse::"
      shell: sh
      if: '!fromJSON(inputs.enable)'
