# SPDX-FileCopyrightText: 2024 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  workflow_dispatch:
  workflow_call:

jobs:
  markdownlint:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

    - name: Enable generic error matcher
      run: echo "::add-matcher::.github/problem-matchers/generic.json"

    - name: Install JS dependencies
      id: npm
      run: npm install

    - name: Lint Markdown files
      run: npm run-script lint:markdownlint
