# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: master

concurrency: ${{ github.ref }}

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      push: true

  pages:
    needs: ci
    if: ${{ !cancelled() && fromJSON(needs.ci.outputs.build-success) }}
    runs-on: ubuntu-slim
    timeout-minutes: 5

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: '{*.shell-extension.zip,ddterm-*.tar.{xz,gz,bz2}{,.*sum},report-*.html,junit-*.xml}'
          skip-decompress: true
          merge-multiple: true

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: 'archlinux-package{,-check}'

      - run: >-
          find . -type d -exec
          bash -c 'tree "$0" -h --du -D -H "/${GITHUB_REPOSITORY#*/}/${0:2}" -o "$0/index.html"' '{}'
          ';'

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: .
          name: github-pages-${{ github.run_attempt }}

      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          artifact_name: github-pages-${{ github.run_attempt }}

  release:
    needs: ci
    if: ${{ !cancelled() && fromJSON(needs.ci.outputs.build-success) && needs.ci.outputs.release-tag && vars.ENABLE_RELEASES }}
    runs-on: ubuntu-slim
    timeout-minutes: 5

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      TAG: ${{ needs.ci.outputs.release-tag }}

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: '{*.shell-extension.zip,ddterm-*.tar.{xz,gz,bz2}{,.*sum},release-notes.md}'
          skip-decompress: true
          merge-multiple: true

      - run: gh release create "$TAG" --draft --notes-file release-notes.md --target "$GITHUB_SHA" ./*.zip ./*.tar.*
