name: pack

on: [push]

jobs:
  pack:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-extension-ddterm-ci-docker-image:master

    steps:
    - uses: actions/checkout@v2
    - run: xvfb-run make pack
    - uses: actions/upload-artifact@v2
      with:
        name: shell-extension
        path: "*.shell-extension.zip"
    - uses: amezin/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "*.shell-extension.zip"
        draft: true
