# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  workflow_dispatch:
    inputs:
      testspace:
        description: 'Publish report to Testspace'
        type: boolean
        default: false
        required: false
  workflow_call:
    inputs:
      testspace:
        description: 'Publish report to Testspace'
        type: boolean
        default: false
        required: false

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  TERM: xterm-color

defaults:
  run:
    shell: bash

jobs:
  archlinux-nocheck:
    runs-on: ubuntu-24.04
    container:
      image: archlinux:base-devel
      options: --privileged --tmpfs /run

    steps:
    - run: pacman -Syu --noconfirm --noprogressbar devtools

    - run: systemd-machine-id-setup

    # https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/197
    - run: sed -i 's/nspawn_args=(/nspawn_args=(--keep-unit /' /usr/bin/arch-nspawn

    - run: useradd -m user

    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # for pkgver()

    - run: chown -R user .

    - run: extra-x86_64-build -- -U user -- --nocheck

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: archlinux-package
        path: |
          *.pkg.tar.*
          !*-namcap.log
        if-no-files-found: error

  archlinux-test-installed:
    needs: archlinux-nocheck
    uses: ./.github/workflows/test.yml
    with:
      package-artifact: archlinux-package
      containers: '["archlinux"]'
      args: --sys-package *.pkg.tar.*
      testspace: ${{ inputs.testspace }}

  archlinux:
    runs-on: ubuntu-24.04
    container:
      image: archlinux:base-devel
      options: --privileged --tmpfs /run

    steps:
    - run: pacman -Syu --noconfirm --noprogressbar devtools

    - run: systemd-machine-id-setup

    # https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/197
    - run: sed -i 's/nspawn_args=(/nspawn_args=(--keep-unit /' /usr/bin/arch-nspawn

    - run: useradd -m user

    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # for pkgver()

    - run: chown -R user .

    - run: extra-x86_64-build -- -U user
