# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: github-pages

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Source workflow run id
        required: true

  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id || inputs.run_id }}
          name: pack
          github-token: ${{ github.token }}

      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id || inputs.run_id }}
          name: archlinux-package
          github-token: ${{ github.token }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  publish:
    needs: build
    if: github.event.workflow_run
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
