# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Deploy pages
        type: boolean
        default: false
        required: false

  workflow_call:
    inputs:
      publish:
        description: Deploy pages
        type: boolean
        default: false
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pack

      - uses: actions/download-artifact@v4
        with:
          name: archlinux-package-nocheck

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  publish:
    needs: build
    runs-on: ubuntu-24.04
    if: ${{ inputs.publish }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
