# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: pot

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false
        description: Push changes to the repository

  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  VIRTUALENV_SYSTEM_SITE_PACKAGES: 'true'
  TERM: xterm-color
  TQDM_DISABLE: 1

jobs:
  update:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    container:
      image: ghcr.io/ddterm/ci-docker-image:2025.04.16.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"

      - name: Install meson
        uses: ./.github/actions/tox-preinstall
        with:
          environments: meson

      - run: |
          echo "$GITHUB_WORKSPACE/.tox/meson/bin" >>"$GITHUB_PATH"
          echo "$GITHUB_WORKSPACE/.github/bin" >>"$GITHUB_PATH"

      - name: Enable generic error matcher
        uses: ./.github/actions/generic-problem-matcher

      - name: Prepare build directory
        run: meson setup build
        shell: faketty.sh bash -e {0}

      - name: Update POTFILES.in
        run: ninja -j1 potfiles
        working-directory: build

      - name: Update .pot file
        run: ninja -j1 pot && ninja -j1 pot-set-year
        working-directory: build

      - name: Update .po files
        run: for pofile in po/*.po; do msgmerge --no-wrap --update --previous "$pofile" po/*.pot; done

      - name: Check if there are any changes
        id: updated-files
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', [
              'diff',
              '--name-only',
              '--ignore-matching-lines=^"POT-Creation-Date: ',
              'po/**',
            ]);

            return stdout.trim();

      - name: Get commit token
        id: app-token
        if: github.secret_source == 'Actions' && !github.event.repository.fork
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Commit
        id: commit
        if: >-
          (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push)) &&
          steps.updated-files.outputs.result &&
          steps.app-token.outcome != 'skipped'

        uses: amezin/create-commit-action@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          message: 'Update translation files'
          files: ${{ steps.updated-files.outputs.result }}

      - name: Update branch
        if: steps.commit.outcome != 'skipped'
        uses: amezin/create-or-update-git-ref-action@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          ref: generated/pot
          sha: ${{ steps.commit.outputs.sha }}
          force: true

      - name: Pull request
        if: steps.commit.outcome != 'skipped'
        uses: amezin/create-or-update-pull-request-action@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          title: 'Update translation files'
          head: generated/pot
