# SPDX-FileCopyrightText: 2023 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pr-po

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  pull_request:
    paths:
      - po/*.po
      - po/*.pot

jobs:
  po:
    uses: ./.github/workflows/check-po.yml

    if: >-
      github.event.pull_request.head.ref == 'weblate'
      || github.event.pull_request.base.repo.node_id != github.event.pull_request.head.repo.node_id
