# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: pr

concurrency: ${{ github.ref }}

on:
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      base: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.repository.default_branch }}

    permissions:
      contents: read
