# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: pr

concurrency: ${{ github.ref }}

on:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
