# SPDX-FileCopyrightText: 2024 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: push-doc

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*
    paths:
      - docs/**
      - README.md
      - .github/workflows/doc.yml
      - .github/workflows/push-doc.yml
      - .markdownlint*

jobs:
  doc:
    uses: ./.github/workflows/doc.yml
