# SPDX-FileCopyrightText: 2025 Aleksandr Mezin <mezin.alexander@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  workflow_dispatch:
    inputs:
      testspace:
        description: 'Publish report to Testspace'
        type: boolean
        default: false
        required: false
  workflow_call:
    inputs:
      testspace:
        description: 'Publish report to Testspace'
        type: boolean
        default: false
        required: false

jobs:
  configure:
    runs-on: ubuntu-24.04

    outputs:
      containers-esm: ${{ steps.config.outputs.esm }}
      containers-legacy: ${{ steps.config.outputs.legacy }}

    steps:
      - uses: actions/checkout@v4

      - id: config
        working-directory: tests
        run: |
          for profile in esm legacy; do
            docker compose --profile $profile config --services | grep -v archlinux | jq -cnR '[inputs]' | sed -e "s/^/$profile=/" >> "$GITHUB_OUTPUT"
          done

  esm:
    needs: configure
    uses: ./.github/workflows/test.yml
    with:
      package-artifact: pack
      containers: ${{ needs.configure.outputs.containers-esm }}
      testspace: ${{ inputs.testspace }}

  legacy:
    needs: configure
    uses: ./.github/workflows/test.yml
    with:
      package-artifact: pack-legacy
      containers: ${{ needs.configure.outputs.containers-legacy }}
      testspace: ${{ inputs.testspace }}
